#!/bin/bash
#
# This file is part of SleepProxyClient.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Andreas Weinlein <andreas.dev@weinlein.info>
# @copyright Copyright (c) 2012-2023 Andreas Weinlein
#
# SleepProxyClient is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# SleepProxyClient is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SleepProxyClient. If not, see <http://www.gnu.org/licenses/>.

. /etc/sleepproxyclient.conf

TAG="sleepproxyclient"
SCRIPTDIR="/usr/share/sleepproxyclient/scripts"

log() 
{
    [ ! -f "$SPC_LOGFILE" ] && return
    d=$(date -Isec)
    [ "$SPC_DEBUG" = "1" ] && echo "$d [$TAG] 00_sleepproxyclient: $1" >> "$SPC_LOGFILE"
}

case $1 in
pre|suspend|hibernate)
## RUN BEFORE SUSPEND OR HIBERNATE
    
    avahi-set-host-name $(hostname)

    log "running sleepproxyclient"
    export SPC_INTERFACES SPC_PREFERRED_PROXIES SPC_LEASE_TIME SPC_LOGFILE SPC_DEBUG
    python3 "$SCRIPTDIR/sleepproxyclient.py"

    if [ -n "${SPC_RTC_WAKE}" -a -e "/sys/class/rtc/${SPC_RTC_WAKE}" ] ; then
        log "setting RTC alarm"
        rtc_time=$((SPC_LEASE_TIME +  60))
        echo `date '+%s' -d "+ ${rtc_time} seconds"` > "/sys/class/rtc/${SPC_RTC_WAKE}/wakealarm"
    fi
    log "done: $?"
;;
post|thaw|resume)
## RUN AFTER RESUME AND
## AFTER RESUME FROM SUSPEND TO DISK
    log "awake!"

	if [ -n "${SPC_RTC_WAKE}" -a -e "/sys/class/rtc/${SPC_RTC_WAKE}" ] ; then
		# Ensure RTC alarm is cleared on wake
		log "clear RTC alarm"
		echo 0 > "/sys/class/rtc/${SPC_RTC_WAKE}/wakealarm"
	fi
;;
esac